# Generated by Django 4.1 on 2022-08-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='producto',
        ),
    ]
