# Generated by Django 4.1 on 2022-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_description_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagen de la categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagen del producto'),
            preserve_default=False,
        ),
    ]
