# Generated by Django 4.1 on 2022-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=200, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
