# Generated by Django 4.1 on 2022-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default='True', verbose_name='Estado'),
        ),
    ]
