# Generated by Django 4.1 on 2022-09-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre/s')),
                ('surname', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('position', models.IntegerField(verbose_name='Posición')),
                ('shirt_number', models.IntegerField(verbose_name='Número de camiseta')),
                ('holder', models.BooleanField(default=True, verbose_name='¿Es titular?')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoccerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Grupo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('flag', models.ImageField(upload_to='', verbose_name='Bandera')),
                ('shield', models.ImageField(upload_to='', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Selección de fútbol',
                'verbose_name_plural': 'Selecciones de fútbol',
                'db_table': 'seleccion_futbol',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre/s')),
                ('surname', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nationality', models.CharField(max_length=120, verbose_name='Nacionalidad(Nombre del país)')),
                ('rol', models.IntegerField(verbose_name='Rol')),
                ('soccer_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soccerteam')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnico',
                'ordering': ['soccer_team'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soccerteam'),
        ),
    ]
