# Generated by Django 4.1 on 2022-09-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_player_soccerteam_technical_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technical',
            options={'ordering': ['rol'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AddField(
            model_name='technical',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soccerteam', verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(1, 'POR'), (2, 'DFC'), (3, 'LD'), (4, 'LI'), (5, 'CAD'), (6, 'CAI'), (7, 'MCD'), (8, 'MD'), (9, 'MC'), (10, 'MI'), (11, 'MCO'), (12, 'ED'), (13, 'EI'), (14, 'DC'), (15, 'SD')], verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='soccerteam',
            name='group',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H')], verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Técnico'), (2, 'Asistente'), (3, 'Médico'), (4, 'Preparador')], verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='soccer_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soccerteam', verbose_name='Selección de fútbol'),
        ),
    ]
